// ImportManifest.cs -- PORT (public build): the proof-of-ownership manifest.
//
// `Assets/import-manifest.json` is generated by
// tools/gen_import_manifest.py from our genuine retail extraction and
// packaged read-only inside the APK.  It lists ONLY original files (data/**,
// gfx/**/*.xnb, gfx/maps/maps.zdx, Resources/**) with size + SHA-256; nothing
// this project derived is ever listed.
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

namespace Dishwasher.Import
{
    public sealed class ImportManifest
    {
        public int Version = 1;
        public string Algorithm = "sha256";
        public List<Entry> Files = new List<Entry>();

        public sealed class Entry
        {
            public string Path;
            public long Size;
            public string Sha256;
        }

        public static ImportManifest Load(Stream json)
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;
            var m = new ImportManifest();
            if (root.TryGetProperty("version", out var v)) m.Version = v.GetInt32();
            if (root.TryGetProperty("algorithm", out var a)) m.Algorithm = a.GetString();
            foreach (var f in root.GetProperty("files").EnumerateArray())
            {
                var e = new Entry
                {
                    Path = f.GetProperty("path").GetString().Replace('\\', '/'),
                    Sha256 = f.GetProperty("sha256").GetString(),
                };
                if (f.TryGetProperty("size", out var s)) e.Size = s.GetInt64();
                m.Files.Add(e);
            }
            return m;
        }
    }
}
